Use docc for documentation, instead of having it all in a single, giant README. (#1135)
* Migrate Nimble's documentation to a DocumentCatalog

* Remove autogenerated docs

* Build docs as part of github

diff --git a/script/release b/script/release
--- a/script/release
+++ b/script/release
@@ -127,11 +127,7 @@ else
 
     git add ${PODSPEC} || { restore_podspec; die "Failed to add ${PODSPEC} to INDEX"; }
 
-    echo "--- Updating Docs ---"
-    ./script/build_docs.zsh
-    git add docs || { git co docs; die "Failed to add docs to INDEX"; }
-
-    git commit -m "[$VERSION_TAG] Update docs and podspec" || { restore_podspec; die "Failed to push updated version: $VERSION"; }
+    git commit -m "[$VERSION_TAG] Update podspec" || { restore_podspec; die "Failed to push updated version: $VERSION"; }
 fi
 
 RELEASE_NOTES="Version ${VERSION}. Open https://github.com/Quick/Nimble/releases/tag/$VERSION_TAG for full release notes."
